name       : mate-power-manager
version    : 1.18.0
release    : 5
source     :
    - https://pub.mate-desktop.org/releases/1.18/mate-power-manager-1.18.0.tar.xz : dd0c5fc82d0ea81246890a95d57de92c60c3d735ad06f5946c79eebe7c52b3be
license    : GPL-2.0
component  : desktop.mate
summary    : Power Managment for the MATE Desktop
description: |
    Power Management for the MATE Desktop
builddeps  :
    - pkgconfig(dbus-glib-1)
    - pkgconfig(gnome-keyring-1)
    - pkgconfig(gtk+-3.0)
    - pkgconfig(libcanberra-gtk3)
    - pkgconfig(libmatepanelapplet-4.0)
    - pkgconfig(libnotify)
    - pkgconfig(mate-desktop-2.0)
    - pkgconfig(unique-3.0)
    - pkgconfig(upower-glib)
    - pkgconfig(x11)
    - pkgconfig(xrender)
    - itstool
setup      : |
    %configure --with-gtk=3.0
build      : |
    %make
install    : |
    %make_install
    mv $installdir/etc/xdg $installdir/usr/share/.
    rmdir $installdir/etc
