name       : mate-power-manager
version    : 1.14.0
release    : 1
source     :
    - http://pub.mate-desktop.org/releases/1.14/mate-power-manager-1.14.0.tar.xz : 2306f7210298dba705277b748f8e3da1481889af4cb047a3eb76f196c4ded898
license    : GPL-2.0
component  : desktop.mate
summary    : Power Managment for the MATE Desktop
description: |
    Power Management for the MATE Desktop
builddeps  :
    - pkgconfig(gtk+-3.0)
    - pkgconfig(gnome-keyring-1)
    - pkgconfig(libcanberra-gtk3)
    - pkgconfig(libmatepanelapplet-4.0)
    - pkgconfig(libnotify)
    - pkgconfig(mate-desktop-2.0)
    - pkgconfig(x11)
    - pkgconfig(xrender)
    - pkgconfig(unique-3.0)
    - pkgconfig(upower-glib)
    - itstool
setup      : |
    %configure --with-gtk=3.0
build      : |
    %make
install    : |
    %make_install
