name       : mate-power-manager
version    : 1.27.0
release    : 23
source     :
    - https://github.com/mate-desktop/mate-power-manager/releases/download/v1.27.0/mate-power-manager-1.27.0.tar.xz : 71284aa579856958112f6e1471662124ba00fe040ec19419353118b8e790728b
license    : GPL-2.0-or-later
component  : desktop.mate
summary    : Power Managment for the MATE Desktop
description: |
    Power Management for the MATE Desktop
builddeps  :
    - pkgconfig(dbus-glib-1)
    - pkgconfig(libcanberra-gtk3)
    - pkgconfig(libmatepanelapplet-4.0)
    - pkgconfig(libnotify)
    - pkgconfig(libsecret-1)
    - pkgconfig(mate-desktop-2.0)
    - pkgconfig(upower-glib)
    - itstool
setup      : |
    %configure --disable-static
build      : |
    %make
install    : |
    %make_install
    mv $installdir/etc/xdg $installdir/usr/share/.
    rmdir $installdir/etc
