name       : mate-power-manager
version    : 1.24.3
release    : 21
source     :
    - https://github.com/mate-desktop/mate-power-manager/releases/download/v1.24.3/mate-power-manager-1.24.3.tar.xz : 861e6ddf9e29f7a9bc8424092b8266c05871302bd04cfb252e83c211e3cdace6
license    : GPL-2.0-or-later
component  : desktop.mate
summary    : Power Managment for the MATE Desktop
description: |
    Power Management for the MATE Desktop
builddeps  :
    - pkgconfig(dbus-glib-1)
    - pkgconfig(gnome-keyring-1)
    - pkgconfig(libcanberra-gtk3)
    - pkgconfig(libmatepanelapplet-4.0)
    - pkgconfig(libnotify)
    - pkgconfig(mate-desktop-2.0)
    - pkgconfig(upower-glib)
    - itstool
setup      : |
    %configure --disable-static
build      : |
    %make
install    : |
    %make_install
    mv $installdir/etc/xdg $installdir/usr/share/.
    rmdir $installdir/etc
