name       : mate-power-manager
version    : 1.20.1
release    : 11
source     :
    - https://pub.mate-desktop.org/releases/1.20/mate-power-manager-1.20.1.tar.xz : d6a965f85ef9bbf45c02a8f8010b7530a6154488c73730c5ea26aacce49686e8
license    : GPL-2.0-only
component  : desktop.mate
summary    : Power Managment for the MATE Desktop
description: |
    Power Management for the MATE Desktop
builddeps  :
    - pkgconfig(dbus-glib-1)
    - pkgconfig(gnome-keyring-1)
    - pkgconfig(libcanberra-gtk3)
    - pkgconfig(libmatepanelapplet-4.0)
    - pkgconfig(libnotify)
    - pkgconfig(mate-desktop-2.0)
    - pkgconfig(upower-glib)
    - pkgconfig(xrender)
    - itstool
setup      : |
    %configure --disable-static
build      : |
    %make
install    : |
    %make_install
    mv $installdir/etc/xdg $installdir/usr/share/.
    rmdir $installdir/etc
