name       : mate-power-manager
version    : 1.18.1
release    : 8
source     :
    - https://pub.mate-desktop.org/releases/1.18/mate-power-manager-1.18.1.tar.xz : 25dbd47c063d9aa2ed4be6401f6650aec11e0baa6bdd5dbb12cbb6952461cbeb
license    : GPL-2.0
component  : desktop.mate
summary    : Power Managment for the MATE Desktop
description: |
    Power Management for the MATE Desktop
builddeps  :
    - pkgconfig(dbus-glib-1)
    - pkgconfig(gnome-keyring-1)
    - pkgconfig(gtk+-3.0)
    - pkgconfig(libcanberra-gtk3)
    - pkgconfig(libmatepanelapplet-4.0)
    - pkgconfig(libnotify)
    - pkgconfig(mate-desktop-2.0)
    - pkgconfig(unique-3.0)
    - pkgconfig(upower-glib)
    - pkgconfig(x11)
    - pkgconfig(xrender)
    - itstool
setup      : |
    %configure --disable-static
build      : |
    %make
install    : |
    %make_install
    mv $installdir/etc/xdg $installdir/usr/share/.
    rmdir $installdir/etc
